//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class driverdetail
    {
        public long id { get; set; }
        public System.Guid driverid { get; set; }
        public string drivername { get; set; }
        public string age { get; set; }
        public string mobileno { get; set; }
        public string address { get; set; }
        public string licanceno { get; set; }
        public string vehicleno { get; set; }
        public string residenceno { get; set; }
        public string familyno { get; set; }
        public string relation { get; set; }
        public string bgroup { get; set; }
        public string bankname { get; set; }
        public string branchname { get; set; }
        public string acno { get; set; }
        public string ifsccode { get; set; }
        public Nullable<bool> isactive { get; set; }
    }
}
