//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_master
    {
        public long id { get; set; }
        public System.Guid driverid { get; set; }
        public string orderstatus { get; set; }
        public string mobileno { get; set; }
        public Nullable<long> orderno { get; set; }
        public string pickupperson { get; set; }
        public string pickupcontact { get; set; }
        public string pickupitem { get; set; }
        public string deliveryperson { get; set; }
        public string deliverycontact { get; set; }
        public string deliveryitem { get; set; }
        public string pickupaddress { get; set; }
        public string deliveryaddress { get; set; }
        public string pickupmessage1 { get; set; }
        public string pickupmessage2 { get; set; }
        public string pickupmessage3 { get; set; }
        public string pickupmessage4 { get; set; }
        public string pickupmessage5 { get; set; }
        public string billingtype { get; set; }
        public string billto { get; set; }
        public string deliverycharge { get; set; }
        public string pob { get; set; }
        public string tocollect { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
        public Nullable<System.DateTime> deliverdate { get; set; }
        public string pickuparea { get; set; }
        public string deliveryarea { get; set; }
        public Nullable<decimal> startpickupkh { get; set; }
        public Nullable<System.DateTime> startpickupdate { get; set; }
        public Nullable<decimal> pickuprichkh { get; set; }
        public Nullable<System.DateTime> pickuprichdate { get; set; }
        public Nullable<System.DateTime> pickupitemdate { get; set; }
        public Nullable<decimal> startdeliverykh { get; set; }
        public Nullable<System.DateTime> startdeliverydate { get; set; }
        public Nullable<decimal> deliveryrichkh { get; set; }
        public Nullable<System.DateTime> deliverydate { get; set; }
        public string collectperson { get; set; }
        public string collectphone { get; set; }
        public string billno { get; set; }
        public string yourorderno { get; set; }
        public string isread { get; set; }
        public string isremove { get; set; }
        public Nullable<bool> isactive { get; set; }
    }
}
