//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utility
    {
        public int id { get; set; }
        public string sitename { get; set; }
        public string sitelogo { get; set; }
        public string siteurl { get; set; }
        public string MailServer { get; set; }
        public string from { get; set; }
        public string cc { get; set; }
        public string username { get; set; }
        public string Password { get; set; }
        public Nullable<int> Authenticate { get; set; }
        public string emailtop { get; set; }
        public string emailbottom { get; set; }
        public Nullable<int> port { get; set; }
        public Nullable<int> pagination { get; set; }
        public string sitebyname { get; set; }
        public string sitebyurl { get; set; }
    }
}
